# Generated by Django 6.0.4 on 2026-06-01 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(help_text='Código hexadecimal del color', max_length=7)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'etiquetas',
            },
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('position', models.IntegerField(verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Columna',
                'verbose_name_plural': 'Columnas',
                'db_table': 'columnas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Rol')),
            ],
            options={
                'verbose_name': 'Rol Maestro',
                'verbose_name_plural': 'Roles Maestros',
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, help_text='Ejemplo: AB-1234 (entre 4 y 12 caracteres, letras, números o especiales)', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\S{4,12}$', 'El ID debe tener entre 4 y 12 caracteres sin espacios.')], verbose_name='ID Único de Proyecto')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_deadline', models.DateField(blank=True, null=True, verbose_name='Fecha Límite (Deadline)')),
                ('tipo', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('BASE_DE_DATOS', 'Base de Datos'), ('DOCUMENTACION', 'Documentación / Análisis'), ('PERSONALIZADO', 'Proyecto Personalizado')], default='PERSONALIZADO', max_length=20, verbose_name='Tipo de Proyecto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('proyecto_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='proyectos.proyecto', verbose_name='Proyecto Padre')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('tipo_reporte', models.CharField(max_length=50, verbose_name='Tipo de Reporte')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Sexo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('rol_maestro', models.ForeignKey(blank=True, db_column='rol_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Perfil de Empleado',
                'verbose_name_plural': 'Perfiles de Empleados',
                'db_table': 'perfiles_empleados',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('column', models.CharField(choices=[('POR_HACER', 'Por Hacer'), ('EN_PROCESO', 'En Proceso'), ('EN_REVISION', 'En Revisión'), ('LISTO', 'Listo / Finalizado')], default='POR_HACER', max_length=20, verbose_name='Columna/Estado')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregables/', verbose_name='Archivo Adjunto')),
                ('assigned_to', models.ForeignKey(db_column='assigned_to', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TareaEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.etiqueta')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.task')),
            ],
            options={
                'verbose_name': 'Relación Tarea-Etiqueta',
                'verbose_name_plural': 'Relaciones Tareas-Etiquetas',
                'db_table': 'tarea_etiquetas',
            },
        ),
        migrations.CreateModel(
            name='HistorialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='proyectos.task')),
            ],
            options={
                'verbose_name': 'Historial de Tarea',
                'verbose_name_plural': 'Historiales de Tareas',
                'db_table': 'historial_tareas',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_dependiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueada_por', to='proyectos.task')),
                ('tarea_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloquea_a', to='proyectos.task')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'db_table': 'dependencias',
            },
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='proyectos.task', verbose_name='Tarea')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiempoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_invertidas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_registro', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='proyectos.task')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tiempo de Tarea',
                'verbose_name_plural': 'Tiempos de Tareas',
                'db_table': 'tiempos_tareas',
            },
        ),
    ]
