# Generated by Django 6.0.4 on 2026-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilempleado',
            name='rol_maestro',
        ),
        migrations.AddField(
            model_name='perfilempleado',
            name='rol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol'),
        ),
    ]
