# Generated by Django 6.0.4 on 2026-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_perfilempleado_rol_maestro_perfilempleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilempleado',
            name='rol',
            field=models.CharField(blank=True, choices=[('GERENTE', 'Gerente'), ('ANALISTA', 'Analista'), ('ANALISTA_ESPECIALIZADO', 'Analista Especializado'), ('DESARROLLADOR', 'Desarrollador')], max_length=50, null=True, verbose_name='Rol'),
        ),
    ]
