# Generated by Django 6.0.4 on 2026-06-05 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_perfilempleado_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempleado',
            name='rol_maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.rol', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='task',
            name='etiquetas_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='tareas_asociadas', through='proyectos.TareaEtiqueta', to='proyectos.etiqueta'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.kanbancolumn', verbose_name='Columna/Estado'),
        ),
        migrations.CreateModel(
            name='ProyectoInhabilitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inhabilitacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inhabilitación')),
                ('inhabilitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Inhabilitado Por')),
                ('proyecto_original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto', verbose_name='Proyecto Original')),
            ],
            options={
                'verbose_name': 'Proyecto Inhabilitado',
                'verbose_name_plural': 'Proyectos Inhabilitados',
                'db_table': 'proyectos_inhabilitados_historial',
            },
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
    ]
