# Generated by Django 6.0.5 on 2026-06-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_remove_perfilempleado_rol_perfilempleado_rol_maestro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilempleado',
            name='rol',
        ),
    ]
