# Generated by Django 6.0.4 on 2026-06-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_remove_perfilempleado_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite (Countdown)'),
        ),
        migrations.AddField(
            model_name='task',
            name='horas_estimadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas Estimadas'),
        ),
    ]
